SELECT CONCAT('/home/grep/src/', a.BOARD_ID, '/', a.FILE_ID, a.FILE_NAME, a.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS a
INNER JOIN (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) AS b ON a.BOARD_ID = b.BOARD_ID
ORDER BY a.FILE_ID DESC