SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN BOOK_SALES AS B
ON A.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE
BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY CATEGORY
ORDER BY CATEGORY