SELECT A.ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS AS A
INNER JOIN 
(SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE "Intact %") AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_OUTCOME NOT LIKE "Intact %"
ORDER BY A.ANIMAL_ID