WITH RECURSIVE HOUR_BASE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM HOUR_BASE WHERE HOUR < 23
)

SELECT B.HOUR AS HOUR, COUNT(DATETIME) AS COUNT
FROM HOUR_BASE AS B
LEFT JOIN ANIMAL_OUTS AS A ON HOUR(DATETIME) = B.HOUR
GROUP BY B.HOUR
ORDER BY B.HOUR