SELECT A.CAR_ID, CAR_TYPE,
    (CASE
        WHEN CAR_TYPE = "세단" THEN ROUND(DAILY_FEE * 30 * 0.97)
        ELSE ROUND(DAILY_FEE * 30 * 0.92)
    END) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN
(SELECT *
FROM (SELECT CAR_ID, 
      (CASE
        WHEN START_DATE < "2022-11-01" AND END_DATE < "2022-11-01" THEN 0
        ELSE 1
       END) AS AVAILABILITY
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS B
GROUP BY CAR_ID
HAVING SUM(B.AVAILABILITY) < 1) AS C
ON A.CAR_ID = C.CAR_ID
WHERE CAR_TYPE = "세단" OR CAR_TYPE = "SUV"
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC